version: "3.9"

services:
  frontend:
    image: joshpat/cloudtopg-frontend:latest
    container_name: cloudtopg-frontend
    ports:
      - "8080:80"
    depends_on:
      - cart
      - order

  cart:
    image: joshpat/cloudtopg-cart:latest
    container_name: cloudtopg-cart
    ports:
      - "5001:5001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/cloudtopg
    depends_on:
      - mongo

  order:
    image: joshpat/cloudtopg-order:latest
    container_name: cloudtopg-order
    ports:
      - "5002:5002"
    environment:
      - MONGO_URL=mongodb://mongo:27017/cloudtopg
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: cloudtopg-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: cloudtopg-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongo

volumes:
  mongo-data:

